const genmega = require('./build/Release/genmega.node')
const bau = require('./bau')

exports.BarcodeScan = genmega.BarcodeScan
exports.BarcodeCancelScan = genmega.BarcodeCancelScan
exports.BillValidatorStatus = genmega.BillValidatorStatus
exports.BillValidatorEnable = genmega.BillValidatorEnable
exports.BillValidatorDisable = genmega.BillValidatorDisable
exports.BillValidatorStack = genmega.BillValidatorStack
exports.BillValidatorReject = genmega.BillValidatorReject
exports.BillValidatorInit = genmega.BillValidatorInit
exports.BAUGetLastError = bau.BAUGetLastError
exports.BAUOpen = bau.BAUOpen
exports.BAUReset = bau.BAUReset
exports.BAUClose = bau.BAUClose
exports.BAUStatus = bau.BAUStatus
exports.BAUSetEnableDenom = bau.BAUSetEnableDenom
exports.BAUEnable = bau.BAUEnable
exports.BAUCancel = bau.BAUCancel
exports.BAUReturnBill = bau.BAUReturnBill
exports.BAUStackBill = bau.BAUStackBill
exports.BAUGetSupportCurrency = bau.BAUGetSupportCurrency