const genmega = require('./build/Release/genmega.node')
const bau = require('./bau')

exports.BarcodeScan = genmega.BarcodeScan
exports.BarcodeCancelScan = genmega.BarcodeCancelScan
exports.BAUGetLastError = bau.BAUGetLastError
exports.BAUOpen = bau.BAUOpen
exports.BAUReset = bau.BAUReset
exports.BAUClose = bau.BAUClose
exports.BAUStatus = bau.BAUStatus
exports.BAUSetEnableDenom = bau.BAUSetEnableDenom
exports.BAUAcceptBill = bau.BAUAcceptBill
exports.BAUCancel = bau.BAUCancel
exports.BAUReject = bau.BAUReject
exports.BAUStack = bau.BAUStack
exports.BAUGetSupportCurrency = bau.BAUGetSupportCurrency
exports.CDUGetLastError = genmega.CDUGetLastErrorV2
exports.CDUOpen = genmega.CDUOpenV2
exports.CDUClose = genmega.CDUCloseV2
exports.CDUStatus = genmega.CDUStatusV2
exports.CDUVerifyLicenseKey = genmega.CDUVerifyLicenseKeyV2
exports.CDUReset = genmega.CDUResetV2
exports.CDUSetCassetteNumber = genmega.CDUSetCassetteNumberV2
exports.CDUDispense = genmega.CDUDispenseV2
exports.CDUPresent = genmega.CDUPresentV2
exports.CDUForceEject = genmega.CDUForceEjectV2
exports.CDUShutterAction = genmega.CDUShutterActionV2
